# Generated by Django 3.0.5 on 2020-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_auto_20200504_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='task',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен изначально'),
        ),
    ]
