# Generated by Django 3.0.5 on 2020-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_diary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['time', 'id'], 'verbose_name': 'Дневник', 'verbose_name_plural': 'Дневники'},
        ),
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
