# Generated by Django 3.0.5 on 2020-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0011_auto_20200506_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='task',
            field=models.TextField(blank=True, null=True, verbose_name='Задача'),
        ),
    ]
