# Generated by Django 3.0.5 on 2020-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0012_auto_20200506_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-time', 'id'], 'verbose_name': 'Дневник', 'verbose_name_plural': 'Дневники'},
        ),
        migrations.AddField(
            model_name='answer',
            name='budget',
            field=models.IntegerField(default=0, help_text="Влияет на баллы 'Бюджет', положительное или отрицательное число", verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='answer',
            name='customer',
            field=models.IntegerField(default=0, help_text="Влияет на баллы 'Заказчик', положительное или отрицательное число", verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='answer',
            name='deadlines',
            field=models.IntegerField(default=0, help_text="Влияет на баллы 'Сроки', положительное или отрицательное число", verbose_name='Сроки'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quality',
            field=models.IntegerField(default=0, help_text="Влияет на баллы 'Качество', положительное или отрицательное число", verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='answer',
            name='team',
            field=models.IntegerField(default=0, help_text="Влияет на баллы 'Команда', положительное или отрицательное число", verbose_name='Команда'),
        ),
    ]
