# Generated by Django 3.0.5 on 2020-05-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0016_remove_rating_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-rating', 'id', 'user__id'], 'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AddField(
            model_name='question',
            name='help',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка для студента'),
        ),
    ]
