# Generated by Django 3.0.5 on 2020-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0018_auto_20200602_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complexity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
